language: node_js
node_js:
  - 0.7
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm install connect
  - sudo node test/lib/node-server.js &
  - sleep 5
script: phantomjs test/lib/phantom-mocha.js "http://localhost:80/test/index.html"